### PR TITLE
Attempt to update the plugin to ES 5.1.1

### PR DESCRIPTION
**Pull request by jcscottiii**
The PR is an attempt to update the plugin to work with ES 5.1.1

## Need a new branch to target instead of `2.4.1`

Extra stuff: My IDE found that some files used both tabs and spaces. As a result some of the files have adjusted some lines to use which ever style was prominent in that file. (not much logic changes)

## Notable Changes

- Move from using `handleRequest` to `prepareRequest`. [Commit it happened in ES Source](https://github.com/elastic/elasticsearch/commit/51d53791fe71c9cb62bc992588a57cdfb500383f#diff-7244f287796f715ce51bcf6c2f86c5b1L60)
- Using Java 1.8 notation for channels and `sendResponse`. [Example of it in ES Source](https://github.com/elastic/elasticsearch/commit/51d53791fe71c9cb62bc992588a57cdfb500383f#diff-3ba05b3d515b832eb286842ca39601dcR69)
- Move the plugin from `extends Plugin` to `implements ActionPlugin`
  - Move from using `onModule` to `getRestHandlers`
- In ES Source, they moved from using `ESLogger` wrapper to `log4j`. This patch does so as well [Commit in ES](https://github.com/elastic/elasticsearch/pull/20235/files)
- `setRefresh` was removed and replaced with `setRefreshPolicy` in ES. Did the same here. [Example in Commit in ES when it was replaced](https://github.com/elastic/elasticsearch/pull/18752/files#diff-3fb51a4c770b1a968a879e40a1fdf58cL64)
- Elasticsearch removed it's own `Base64` implementation in favor of the one in Java `java.util.Base64`

### CODE REVIEW

**Comment by jcscottiii** [comment]
# Big TODO: Need to actually try this out

**Comment by lmangani** [comment]
This week is Epic! Thanks @jcscottiii 
Could you please point the PR at branch 5.1.1 (just a clone of 2.4.1) so we can merge & test it?

**Comment by jcscottiii** [comment]
@lmangani done! :)

**Comment by jcscottiii** [comment]
@lmangani any testing assistance would be great !! :)

**Pull request merged**
